-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, 
    COUNT(DISTINCT T1.USER_ID) AS USERS
FROM USER_INFO AS T1
INNER JOIN ONLINE_SALE AS T2
    ON T1.USER_ID = T2.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;